### ISSUE TITLE
Want play store 

### ISSUE THREAD

**Issue by Lunga3r** [awebre/la-historical-markers#77]
Doesn't want install play store

**Comment by awebre** [comment]
Hey, thanks for reaching out! I'm currently working with Google to get our Play Store listing back up. They took us offline suddenly because our Privacy Policy wasn't listed directly in the app. I'll be posting any updates related to that here: #71

**Comment by awebre** [comment]
@Lunga3r Just an update on this. We were finally approved for internal testing via the Play Store. If you'd like to try a beta version of the app on Android you can sign up for our Beta:
https://play.google.com/apps/testing/com.austinwebre.lahistoricalmarkers

There is currently an issue with a crash that I should have fixed shortly 😁
